// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihlxilmnbzxxpeysvflu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobHhpbG1uYnp4eHBleXN2Zmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NTAxMTYsImV4cCI6MjA4NDIyNjExNn0.Ch4el2y1qoec9jE9u1q3EsPkzb1Ag9cx-PQ9SXVeeoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});